apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: 30080
      {{- end }}
  selector:
    app: myapp
