name: Terraform Multi-Env Pipeline with KinD + Security + App Test

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches:
      - "*"   # Any branch push triggers pipeline

jobs:
  validate:
    name: Validate Terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform -chdir=terraform init -backend=false

      - name: Terraform Validate
        run: terraform -chdir=terraform validate

      - name: TFLint (Static Analysis)
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          tflint --chdir=terraform

  security:
    name: Security Scan (Checkov)
    runs-on: ubuntu-latest
    needs: [validate]
    steps:
      - uses: actions/checkout@v2
      - name: Run Checkov (Terraform IaC Security Scan)
        run: |
          pip install checkov
          checkov -d terraform

  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: [security]
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2

      - name: Install KinD
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind
          kind create cluster --name demo
          kubectl cluster-info

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Plan
        run: terraform -chdir=terraform plan -input=false

  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs: [plan]
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2

      - name: Install KinD
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind
          kind create cluster --name demo
          kubectl cluster-info

      - name: Terraform Init (Dev)
        run: terraform -chdir=terraform init

      - name: Terraform Apply (Dev)
        run: terraform -chdir=terraform apply -auto-approve

      - name: Smoke Test
        run: kubectl get ns

      - name: Deploy Nginx App
        run: |
          kubectl create deployment nginx --image=nginx -n demo-namespace
          kubectl expose deployment nginx --port=80 --target-port=80 -n demo-namespace

      - name: Health Check
        run: |
          kubectl wait --for=condition=available --timeout=60s deployment/nginx -n demo-namespace
          kubectl get pods -n demo-namespace

  image-scan:
    name: Container Security Scan (Trivy)
    runs-on: ubuntu-latest
    needs: [deploy-dev]
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/myapp:latest ./helm/myapp
          docker push ghcr.io/${{ github.repository }}/myapp:latest

      - uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ github.repository }}/myapp:latest
          severity: CRITICAL,HIGH
          ignore-unfixed: true

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [image-scan]
    environment:
      name: staging
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2

      - name: Install KinD
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind
          kind create cluster --name demo
          kubectl cluster-info

      - name: Terraform Init (Staging)
        run: terraform -chdir=terraform init

      - name: Terraform Apply (Staging)
        run: terraform -chdir=terraform apply -auto-approve

      - name: Deploy Nginx App
        run: |
          kubectl create deployment nginx --image=nginx -n demo-namespace
          kubectl expose deployment nginx --port=80 --target-port=80 -n demo-namespace

      - name: Integration Tests
        run: |
          kubectl wait --for=condition=available --timeout=60s deployment/nginx -n demo-namespace
          kubectl get pods -n demo-namespace

  deploy-prod:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    needs: [deploy-staging]
    environment:
      name: production
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2

      - name: Install KinD
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind
          kind create cluster --name demo
          kubectl cluster-info

      - name: Terraform Init (Prod)
        run: terraform -chdir=terraform init

      - name: Terraform Apply (Prod)
        run: terraform -chdir=terraform apply -auto-approve

      - name: Deploy Nginx App
        run: |
          kubectl create deployment nginx --image=nginx -n demo-namespace
          kubectl expose deployment nginx --port=80 --target-port=80 -n demo-namespace

      - name: Monitoring Check
        run: |
          kubectl wait --for=condition=available --timeout=60s deployment/nginx -n demo-namespace
          kubectl get pods -n demo-namespace
